version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PMS
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pms-net

  eureka-server:
    build: ./discovery-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - pms-net

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
      - doctor-service
      - appointment-service
      - billing-service
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

  swagger-aggregator:
    build: ./swagger-aggregator
    container_name: swagger-aggregator
    ports:
      - "9090:9090"
    depends_on:
      - patient-service
      - doctor-service
      - appointment-service
      - billing-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pms-net

volumes:
  mysql_data:

networks:
  pms-net:
