apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot-services'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['patient-service:8081', 'doctor-service:8082', 'appointment-service:8083', 'billing-service:8084']
